In [1]:
import numpy as np
p_out_min = [0.01, 0.02, 0.03, 0.1, 0.3]
p_out_max = [0.1, 0.2, 0.3, 0.5, 0.7]
p_run_max = 0.9
p_run_min = 0.3

runs=[1,2,3,4,6]
def get_probs(w,a):
  p_w = p_out_max[a] + (p_out_min[a]-p_out_max[a])*((w-1)/9)
  p_r = p_run_min + (p_run_max-p_run_min)*((w-1)/9)
  return p_w, p_r

def Calculate_Value(V_in):
	Q_out=np.zeros((max_wickets,5),dtype=float)
	V_out=np.zeros(np.size(V_in),dtype=float)
	shot=np.zeros(np.size(V_in),dtype=int)
	print(np.size(V_out))
	for i in range(1,np.size(V_in)):
		for a in range(np.size(runs)):
			[p_w,p_r]=get_probs(i,a)
			Q_out[i][a]=(1-p_w) * ( p_r*(runs[a]+V_in[i]) + (1-p_r)* (0+V_in[i]) ) + p_w*V_in[i-1]
		V_out[i]=np.max(Q_out[i,:])
		shot[i]=runs[np.argmax(Q_out[i,:])]
	return shot, V_out, Q_out

max_balls=300
max_wickets=11
V=np.zeros((max_balls,max_wickets),dtype=float)
Q=np.zeros((max_balls,max_wickets,5),dtype=float)
PI=np.zeros((max_balls,max_wickets),dtype=int)
PI[max_balls-1,:],V[max_balls-1,:],Q[max_balls-1,:] = Calculate_Value(np.zeros((max_wickets),dtype=float))

for i in range(max_balls-2,-1,-1):
  PI[i,:],V[i,:], Q[i,:,:]=Calculate_Value(V[i+1,:])
  print(i,PI[i,: ])
  print(i,V[i,: ])
  print(i,Q[i,:,: ])


def Calculate_values(V_in):
	Q_out = np.zeros((max_wickets,5),dtype = float)
	V_out = np.zeros(np.size(V_in),dtype = float)
	shot = np.zeros(np.size(V_in),dtype = float)

	for i in range(max_wickets):
		for a in range(np.size(runs)):
			[p_w,p_r] = get_probs(i,a)
			Q_out[i][a] = (1 - p_w)*(p_r*(runs[a] + V_in[i]) + (1-p_r)*(V_in[i])) + p_w(V_in[i-1])
		V_out[i] = np.max(Q_out[i,:])
		shot[i] = runs[np.argmax(Q_out[i,:])]
	return shot,V_out,Q_out






11
11
298 [0 3 3 3 4 6 6 6 6 6 6]
298 [0.         1.071      1.55929    1.95648296 2.4642716  3.07945679
 3.79688889 4.58859259 5.4545679  6.39481481 7.40933333]
298 [[0.         0.         0.         0.         0.        ]
 [0.837      0.984      1.071      0.915      0.729     ]
 [1.12109667 1.37319333 1.55929    1.52270741 1.44736667]
 [1.40198815 1.71390222 1.95648296 1.95196584 1.89878807]
 [1.74545185 2.1209037  2.42635556 2.4642716  2.44175309]
 [2.13764444 2.58284444 2.96004444 3.05619753 3.07945679]
 [2.56811111 3.08844444 3.54544444 3.71407407 3.79688889]
 [3.03617778 3.63635556 4.18053333 4.43437037 4.58859259]
 [3.54184444 4.22657778 4.86531111 5.21708642 5.4545679 ]
 [4.08511111 4.85911111 5.59977778 6.06222222 6.39481481]
 [4.66597778 5.53395556 6.38393333 6.96977778 7.40933333]]
11
297 [0 3 3 3 4 4 6 6 6 6 6]
297 [ 0.          1.3797      2.2304517   2.84915665  3.5447491   4.41752675
  5.43856022  6.62552099  7.92891084  9.34872977 10.88497778]
297 [[ 0.          0.    

In [4]:
import csv
import numpy as np
# from google.colab import drive
# drive.mount('/content/drive')
# np.savetxt("/content/drive/My Drive/test.csv", PI, delimiter=",")


In [5]:
print('Balls Left','\t',end="")
for j in range(max_wickets):
  print(f'W={j}','\t',end="")
print('\n')

for i in range(max_balls):
  print(300-i,'\t',end="")
  for j in range(max_wickets):
    print(f'{V[i][j]:2.2f}','\t',end="")
  print('\n')

Balls Left 	W=0 	W=1 	W=2 	W=3 	W=4 	W=5 	W=6 	W=7 	W=8 	W=9 	W=10 	

300 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.50 	121.00 	208.23 	

299 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.50 	121.00 	208.21 	

298 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.50 	120.99 	208.19 	

297 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.98 	208.17 	

296 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.98 	208.15 	

295 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.97 	208.13 	

294 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.96 	208.11 	

293 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.95 	208.09 	

292 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.95 	208.07 	

291 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.94 	208.05 	

290 	0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.93 	208.02 	

289 	0.00 	2.70 	

In [6]:
for j in range(max_wickets):
  print(f'W={j}','\t',end="")
print('\n')

for i in range(max_balls):
  for j in range(max_wickets):
    print(f'{V[i][j]:2.2f}','\t',end="")
  print('\n')

W=0 	W=1 	W=2 	W=3 	W=4 	W=5 	W=6 	W=7 	W=8 	W=9 	W=10 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.50 	121.00 	208.23 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.50 	121.00 	208.21 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.50 	120.99 	208.19 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.98 	208.17 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.98 	208.15 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.97 	208.13 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.96 	208.11 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.95 	208.09 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.95 	208.07 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.94 	208.05 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.49 	120.93 	208.02 	

0.00 	2.70 	6.41 	11.39 	18.03 	26.91 	38.94 	55.74 	80.48 	120.92 	208.00 	

0.00 	

In [7]:
for i in range(max_balls):
  for j in range(max_wickets):
    print(PI[i][j],'\t',end="")
  print('\n')

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 	1 	1 	1 	2 	

0 	1 	1 	1 	1 	1 	1 