In [45]:
import numpy as np
import math

In [50]:
num_samples = 10000
num_arms = 4
mean = np.random.rand(num_arms,)
sigma = 1
sorted_mean = np.sort(mean)
Delta = sorted_mean[-1]-sorted_mean[-2]

In [51]:
class EE21B063_ETC:
    def __init__(self,num_arms,num_samples,sigma):
        self.__num_arms = num_arms
        self.__num_samples = num_samples
        self.__sigma = sigma
        self.pred_mean = np.zeros(4,dtype = float)
        self.init_action = []
        self.prev_action = -1
        self.m = math.ceil((num_samples**(2.0/3))*(2*np.log(2*num_samples))**(1/3.0))
        for i in range(self.__num_arms):
            for j in range(int(self.m)): 
                self.init_action.append(i)
                
        self.ptr = 0

    def get_action(self,reward):
        
        # write your code here and return the action
        if(self.ptr < self.m*self.__num_arms):
            if(self.prev_action != -1):
                self.pred_mean[self.prev_action] = self.pred_mean[self.prev_action] + reward
                cur_action = self.init_action[self.ptr]
                self.ptr = self.ptr + 1
                self.prev_action = cur_action
                return cur_action
            else: 
                self.prev_action = 0
                self.ptr = self.ptr + 1
                return 0
        else:
            if(self.ptr == self.m*self.__num_arms):
                self.pred_mean[self.prev_action] = self.pred_mean[self.prev_action] + reward
                for i in range(self.__num_arms): self.pred_mean[i] = self.pred_mean[i]/self.m
                self.ptr = self.ptr + 1
            return np.argmax(self.pred_mean)


In [52]:
class Environment:
  def __init__(self,num_arms,mean,sigma,agent):
    self.__num_samples = num_samples
    self.__num_arms = num_arms
    self.__mean = mean
    self.__reward = -100
    self.__action = np.zeros((num_samples,),dtype = int)
    self.__agent = agent
    self.__regret = 0

  def run(self):
    for i in range(self.__num_samples):
      self.__action[i] = self.__agent.get_action(self.__reward)
      self.__reward = self.__mean[self.__action[i]]+sigma*np.random.randn()
    return self.__action



In [53]:
agent = EE21B063_ETC(num_arms,num_samples, sigma)
env = Environment(num_arms,mean,sigma,agent)
action_list= env.run()
print(mean)
print(agent.m)
print(agent.pred_mean)
action_list

[0.243396   0.94489798 0.02752703 0.69033414]
1256
[ 0.28271337  0.94104672 -0.00606583  0.66920496]


array([0, 0, 0, ..., 1, 1, 1])